version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"

  - package-ecosystem: "terraform"
    directory: "/proxmox/vm"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:15"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"

  - package-ecosystem: "terraform"
    directory: "/proxmox/vm-multi"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:20"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"

  - package-ecosystem: "terraform"
    directory: "/proxmox/lxc"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:25"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
